# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Urban Health Project
email: urbanhealthproject@gmail.com
description: Urban Health Project educates, inspires, and challenges medical students through their service to vulnerable populations in Greater Cincinnati to produce more socially responsible physicians who have a greater understanding of factors that impact health.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://urbanhealthproject.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Generate pages from data
# Generate folders not pages - true
page_gen-dirs: true
page_gen:
  - data: 'siteinfo'
    template: 'site_template'
    name: 'full_name'
    dir: 'sites'

# Build settings
#markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed